spring:
  application:
    name: cool-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key:
      chat:
        options:
          model: qwen-plus-2025-09-11
    mcp:
      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8227

server:
  port: 8223
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.coolboy.coolaiagent.controller
# knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh_cn
# Spring AI日志
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

# searchAPI
search-api:
  # 需要替换为你自己的 key
  api-key: 你的 API Key

